### PR TITLE
add package for contact

### PR DESCRIPTION
**Pull request by Neo-Oli**
I've written a contact management program. It allows cool things such these on Termux:

termux-telephony-call "$(contact)" #call someone in you address book
termux-sms-send -n "$(contact get 'Max Muster' mobile)" "Hello friend" #send an sms to someone

### CODE REVIEW

**Comment by caesarleroux** [comment]
@Neo-Oli Yes and that is how it should be otherwise every Tom, Dick and Harry could commit a package that is malicious and that is why I am the only person allowed to actually commit packages to the Atomic package repo. Try to run your fork with `make build`. If it succeeds then that is all I am inerested in.

**Comment by Neo-Oli** [comment]
@caesarleroux It builds successfully before the error. You can see this here: https://travis-ci.org/caesarleroux/atomic/builds/383085169#L726

Can you not make it so that only commits to the master branch have this additional step of uploading to the repository? Then only things that you do or you merge actually get deployed, but it won't show Travis errors on all pull requests.

**Comment by caesarleroux** [comment]
@Neo-Oli 
Seems like a sound suggestion maybe you could suggest what to add to my Travis spec file? I am no Git or Travis CI wizard LOL.

**Comment by Neo-Oli** [comment]
Is travis actually able to upload if it's your commits or do you have to run `make upload` manually?

**Comment by caesarleroux** [comment]
No if it is my commits the `make upload` routine works.

**Pull request merged**
